FROM gnosian/ci-env-dotnet:latest
#FROM mcr.microsoft.com/vscode/devcontainers/universal:linux AS build-environment

#USER root

# Install CICEE and make sure .NET global tools are added to path
#RUN dotnet tool install -g cicee
#ENV PATH="${PATH}:/root/.dotnet/tools"
RUN dotnet tool update -g cicee
